name: 'Rustdoc coverage'
description: 'Generate rustdoc coverage report'
author: 'bewee'
inputs:
  use-cross:
    description: Use cross instead of cargo
    default: false
    required: false
  working-directory:
    description: Select a custom working directory
    required: false
outputs:
  documented:
    description: 'The overall percentage of documented code'
  examples:
    description: 'The overall percentage of code with examples'
  table:
    description: 'Tabular rustdoc coverage summary'
  json:
    description: 'JSON rustdoc coverage summary'
runs:
  using: 'node12'
  main: 'dist/index.js'
